<?php
define('_DB_SERVER_', 'localhost');
define('_DB_NAME_', 'et3t56hd_ty4yhrt');
define('_DB_USER_', 'et3t56hd_ty4yhrt');
define('_DB_PASSWD_', '5SP8VN!8(R');
define('_DB_PREFIX_', 'ps_');
define('_MYSQL_ENGINE_', 'InnoDB');
define('_PS_CACHING_SYSTEM_', 'CacheMemcache');
define('_PS_CACHE_ENABLED_', '0');
define('_MEDIA_SERVER_1_', '');
define('_MEDIA_SERVER_2_', '');
define('_MEDIA_SERVER_3_', '');
define('_COOKIE_KEY_', '7oidjphsddifpjcfuhewbn1h0vpmk0hn0ud94ftd9zfvflwbfycrg9gh');
define('_COOKIE_IV_', 'ootbda70');
define('_PS_CREATION_DATE_', '2014-10-22');
if (!defined('_PS_VERSION_'))
	define('_PS_VERSION_', '1.6.0.9');
define('_RIJNDAEL_KEY_', 'jB5q5Vxt0BThuyMccefoUQJTTXeyBcNx');
define('_RIJNDAEL_IV_', 'p3culIzv3686KJzNOYYoJg==');
